version: "3.3"
services:
  web:
    image: mongo-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: test
      MONGO_USERNAME:
      MONGO_PASSWORD:
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"